name: mcyt
services:
  mcyt:
    container_name: mcyt
    restart: unless-stopped
    image: zoeyvid/mcyt:latest # or ghcr.io/zoeyvid/mcyt:latest
    pull_policy: always
    network_mode: bridge
    ports:
      - "25599:25599"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
      YTPARTY_RELAY_PASSWORD:
      # YTPARTY_DEFAULT_PUBLIC: false
      # YTPARTY_PUBLIC_JOIN_LEVEL: listen  # listen | invite | manage
