name: ytparty
services:
  ytparty:
    container_name: ytparty
    restart: unless-stopped
    image: zoeyvid/ytparty:latest # or ghcr.io/zoeyvid/ytparty:latest
    pull_policy: always
    network_mode: bridge
    ports:
      - "25599:25599"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
      YTPARTY_RELAY_PASSWORD:
