plugins {
    id 'java'
}

group = project.group
version = project.version

java {
    toolchain { languageVersion = JavaLanguageVersion.of(8) }
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly 'org.bukkit:bukkit:1.8-R0.1-SNAPSHOT'
}

processResources {
    def props = [version: project.version]
    inputs.properties props
    filesMatching('plugin.yml') { expand props }
}
