plugins {
    id 'java'
}

version = findProperty('buildVersion') ?: 'develop'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(8) }
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly 'org.bukkit:bukkit:1.8-R0.1-SNAPSHOT'
}

processResources {
    inputs.property 'version', version
    filesMatching('plugin.yml') { expand version: version }
}
