name: plugin
on:
  push:
    branches:
      - develop
    paths:
      - plugin/**
      - .github/workflows/plugin.yml
  pull_request:
    paths:
      - plugin/**
      - .github/workflows/plugin.yml
  workflow_dispatch:
jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: corretto
          java-version: |
            8
            25
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-disabled: true
      - name: date
        id: date
        run: echo "value=$(date +%Y-%m-%d)-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - name: build
        working-directory: plugin
        run: ./gradlew build --no-daemon --stacktrace -Dorg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64 -PbuildVersion=${{ steps.date.outputs.value }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: plugin/build/libs/*.jar
          archive: false
          if-no-files-found: error
          retention-days: 3
      - uses: Kir-Antipov/mc-publish@52307b03863581dec6b652b83e597aec02ebb075 # v3.3.1
        if: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
        with:
          version-type: release
          modrinth-featured: true
          github-prerelease: false
          name: Plugin ${{ steps.date.outputs.value }}
          version: plugin-${{ steps.date.outputs.value }}
          github-tag: plugin-${{ steps.date.outputs.value }}
          files: plugin/build/libs/*.jar
          java: |
            8
            11
            16
            17
            21
            25
          loaders: |
            bukkit
            spigot
            paper
            purpur
            folia
          game-versions: |
            >=1.8
          modrinth-id: ohwyynXQ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
