name: plugin
on:
  push:
    branches:
      - develop
    paths:
      - plugin/**
      - .github/workflows/plugin.yml
  pull_request:
    paths:
      - plugin/**
      - .github/workflows/plugin.yml
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: corretto
          java-version: |
            8
            25
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-disabled: true
      - name: date
        id: date
        run: echo "value=$(date +%Y-%m-%d)-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
      - name: build
        working-directory: plugin
        run: ./gradlew build --no-daemon --stacktrace -Dorg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64 -PbuildVersion=${{ steps.date.outputs.value }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: plugin/build/libs/*.jar
          archive: false
          if-no-files-found: error
          retention-days: 3
      - uses: Kir-Antipov/mc-publish@52307b03863581dec6b652b83e597aec02ebb075 # v3.3.1
        if: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
        with:
          version-type: release
          modrinth-featured: true
          github-prerelease: false
          name: Plugin ${{ steps.date.outputs.value }}
          version: plugin-${{ steps.date.outputs.value }}
          github-tag: plugin-${{ steps.date.outputs.value }}
          files: plugin/build/libs/*.jar
          java: |
            8
            11
            16
            17
            21
            25
          loaders: |
            bukkit
            spigot
            paper
            purpur
            folia
          game-versions: |
            >=1.8
          modrinth-id: ohwyynXQ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
